name: Deploy to sguazzi.org 

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build your Astro site 
        uses: withastro/action@v4
      - name: Sync with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }} 
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: /
          dry-run: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
